### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by zjkzsb** [Zhiquan-Wen/D-VQA#1]
您好，尊敬的技术共享者，我在运行您的程序时缺少dictionary.pkl文件，您看能不能私发一下呢，或者网盘任何渠道都可以，我的邮箱15369310668@163.com,多谢

**Comment by Zhiquan-Wen** [comment]
When you run the code "python create_dictionary.py --dataroot vqacp2/", you would obtain the dictionary.pkl saved in the path of vqacp2/
