### ISSUE TITLE
Vision bias

### ISSUE THREAD

**Issue by SakerLiu** [Zhiquan-Wen/D-VQA#2]
您好，请问一下，您论文中所讲的视觉偏差有没有因为偏差带来的错误的实例，看您的figure 1，这个仅仅能反映VQA模型大多关注salient区域，那么偏差呢，谢谢。

**Comment by Zhiquan-Wen** [comment]
语言偏差通常是指句子与文本之间存在虚假相关性。类似地，我们这描述的视觉偏差是指答案通常是图片中最显著的物体或者属性，比如图片中最显著的物体是黄色的香蕉（物体：banana，属性：yellow），不管question问的是什么，普通VQA模型可能都会回答banana/yellow；当问题的答案恰好就是banana/yellow的时候，模型刚好回答对了，这就无法区分模型是真的理解了问题，还是利用了vision bias；检验的方式就是问一个与答案banana/yellow无关的问题，这时候vision bias带来的影响就能反映出来了；有兴趣的话可以自行找一个预训练的VQA模型，针对一张图片从多个角度提问，这样能比较直观地观察到vision bias的影响。

当然，现在的VQA模型性能还是不错的，上面的例子可能会比较极端。但过分关注图片中显著区域显然是不利的，因此我们想尽可能削弱这方面的影响。

**Comment by SakerLiu** [comment]
那这个其实是跟《Greedy Gradient Ensemble for Robust Visual Question Answering》中提到的shortcut biase很像了


| |
Shandong University
|
|
***@***.***
|
签名由网易邮箱大师定制
On 12/10/2021 17:13，Zhiquan ***@***.***> wrote：

语言偏差通常是指句子与文本之间存在虚假相关性。类似地，我们这描述的视觉偏差是指答案通常是图片中最显著的物体或者属性，比如图片中最显著的物体是黄色的香蕉（物体：banana，属性：yellow），不管question问的是什么，普通VQA模型可能都会回答banana/yellow；当问题的答案恰好就是banana/yellow的时候，模型刚好回答对了，这就无法区分模型是真的理解了问题，还是利用了vision bias；检验的方式就是问一个与答案banana/yellow无关的问题，这时候vision bias带来的影响就能反映出来了；有兴趣的话可以自行找一个预训练的VQA模型，针对一张图片从多个角度提问，这样能比较直观地观察到vision bias的影响。

当然，现在的VQA模型性能还是不错的，上面的例子可能会比较极端。但过分关注图片中显著区域显然是不利的，因此我们想尽可能削弱这方面的影响。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Zhiquan-Wen** [comment]
不太一样，我们这里的vision bias强调的是图片和答案之间可能存在一种虚假相关性（图片中显著的物体或者属性往往对应着答案）。

《Greedy Gradient Ensemble for Robust Visual Question Answering》这篇论文的shortcut bias强调的其实还算是语言偏差，因为他的shortcut bias主要是认为模型即使回答正确，但是却没有关注到正确的图片位置。从这个过程来理解的话，那就是即使给你的是错误的图片信息，模型也能回答正确，这也算是语言偏差的原因导致的。

**Comment by SakerLiu** [comment]
哦哦，明白了，谢谢您的回复


| |
Shandong University
|
|
***@***.***
|
签名由网易邮箱大师定制
On 12/10/2021 17:34，Zhiquan ***@***.***> wrote：

不太一样，我们这里的vision bias强调的是图片和答案之间可能存在一种虚假相关性（图片中显著的物体或者属性往往对应着答案）。

《Greedy Gradient Ensemble for Robust Visual Question Answering》这篇论文的shortcut bias强调的其实还算是语言偏差，因为他的shortcut bias主要是认为模型即使回答正确，但是却没有关注到正确的图片位置。从这个过程来理解的话，那就是即使给你的是错误的图片信息，模型也能回答正确，这也算是语言偏差的原因导致的。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
