### ISSUE TITLE
代码问题咨询

### ISSUE THREAD

**Issue by SakerLiu** [Zhiquan-Wen/D-VQA#3]
您好，您在论文中提到测试阶段的时候使用的是基本的VQAmodel，但是为什么在调用compute_predict的时候却将Need_debias设置为true

**Comment by Zhiquan-Wen** [comment]
您好，感谢您提出的问题。
其实在测试阶段计算score的时候我们取的logits就是基本VQAmodel的输出结果。不论Need_debias设置为True或者False对最后的结果计算其实没有影响，因为我们没有对其他branch的输出做额外的计算score的操作，并且这些额外的branch对基本VQAmodel输出的结果没有影响，所以我们就忽略了这一点。具体您可以看这一行https://github.com/Zhiquan-Wen/D-VQA/blob/dec36fd72f8b63d8f8063faac787440757224eae/test.py#L49，我们只取了基本VQAmodel的输出做计算。

**Comment by SakerLiu** [comment]
好的，明白了，谢谢您的回复
