### ISSUE TITLE
代码复现问题

### ISSUE THREAD

**Issue by SakerLiu** [Zhiquan-Wen/D-VQA#4]
您好，我直接用您公开的代码跑第一个表的结果时，发现无法达到您论文中报的结果，不知道是否是您公开代码的参数有改变还是？
![image](https://user-images.githubusercontent.com/30914380/156949322-7bf10066-86e3-4900-bbbd-9f63df8e83ba.png)

**Comment by Zhiquan-Wen** [comment]
您好，我公开代码的参数是没问题的。我这边是可以复现的，而且训练好的模型以及预测的结果（.json文件）也公布出来了。
我这边的运行环境如下，您看看是否是因为环境不一的问题？

```
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 20.04.4 LTS
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
CMake version: version 3.16.3

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: NVIDIA TITAN Xp
GPU 1: NVIDIA TITAN Xp
GPU 2: NVIDIA TITAN Xp
GPU 3: NVIDIA TITAN Xp
GPU 4: NVIDIA TITAN Xp
GPU 5: NVIDIA TITAN Xp
GPU 6: NVIDIA TITAN Xp
GPU 7: NVIDIA TITAN Xp

Nvidia driver version: 470.103.01
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.1.0
[pip3] torchvision==0.3.0
[conda] torch                     1.1.0                     <pip>
[conda] torchvision               0.3.0                     <pip>
```
预测结果如下：
![image](https://user-images.githubusercontent.com/30120427/156996827-d17ba2a8-99d9-4de5-9cbb-0d8658093bbe.png)

**Comment by SakerLiu** [comment]
因为机器限制，只有1080ti和3090的卡，可能是因为环境的问题？我再调试一下




| |
Shandong University
|
|
***@***.***
|
签名由网易邮箱大师定制
在2022年3月7日 16:41，Zhiquan ***@***.***> 写道：

您好，我公开代码的参数是没问题的。我这边是可以复现的，而且训练好的模型以及预测的结果（.json文件）也公布出来了。
我这边的运行环境如下，您看看是否是因为环境不一的问题？

PyTorch version: 1.1.0

Is debug build: No

CUDA used to build PyTorch: 9.0.176



OS: Ubuntu 20.04.4 LTS

GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

CMake version: version 3.16.3



Python version: 3.6

Is CUDA available: Yes

CUDA runtime version: Could not collect

GPU models and configuration: 

GPU 0: NVIDIA TITAN Xp

GPU 1: NVIDIA TITAN Xp

GPU 2: NVIDIA TITAN Xp

GPU 3: NVIDIA TITAN Xp

GPU 4: NVIDIA TITAN Xp

GPU 5: NVIDIA TITAN Xp

GPU 6: NVIDIA TITAN Xp

GPU 7: NVIDIA TITAN Xp



Nvidia driver version: 470.103.01

cuDNN version: Could not collect



Versions of relevant libraries:

[pip3] numpy==1.19.5

[pip3] torch==1.1.0

[pip3] torchvision==0.3.0

[conda] torch                     1.1.0                     <pip>

[conda] torchvision               0.3.0                     <pip>



预测结果如下：


—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alice-cool** [comment]
我在up_down+d_vqa 跑，最高时在第20epoch 是59.53，后面几轮就开始降了一直降到34.36，这个是正常现象吗？

**Comment by SakerLiu** [comment]
是正常现象，说明模型开始过度估计偏差了应该。。。我这边也是这样


| |
Shandong University
|
|
***@***.***
|
在2022年3月25日 ***@***.***> 写道：

我在up_down+d_vqa 跑，最高时在第20epoch 是59.53，后面几轮就开始降了一直降到34.36，这个是正常现象吗？

**Comment by alice-cool** [comment]
谢谢您的回复



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月25日(星期五) 下午4:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zhiquan-Wen/D-VQA] 代码复现问题 (Issue #4)




 是正常现象，说明模型开始过度估计偏差了应该。。。我这边也是这样
 
 
 | |
 Shandong University
 |
 |
 ***@***.***
 |
 在2022年3月25日 ***@***.***&gt; 写道：
 
 我在up_down+d_vqa 跑，最高时在第20epoch 是59.53，后面几轮就开始降了一直降到34.36，这个是正常现象吗？

**Comment by alice-cool** [comment]
能否问一下，运行LXMERT 时候出现下面的问题，有见过吗
LXRT encoder with 9 l_layers, 5 x_layers, and 5 r_layers.
BertAdam Total Iters: 136940
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/byd/D-VQA-master/LXMERT/src/tasks/main.py", line 271, in <module>
    vqa.train(vqa.train_loader, vqa.val_loader)
  File "/home/byd/D-VQA-master/LXMERT/src/tasks/main.py", line 164, in train
    for i, (feats, boxes, sent, target, ques_id) in tqdm(enumerate(train_loader)):
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/byd/D-VQA-master/LXMERT/src/dataset_vqacp_lxmert.py", line 218, in __getitem__
    feature = self.m.fetchone(colletion_id=true_feature_id, object_id=1)
  File "/home/byd/D-VQA-master/LXMERT/mio/reader.py", line 55, in fetchone
    return self._fetch(colletion_id, object_id)
  File "/home/byd/D-VQA-master/LXMERT/mio/reader.py", line 75, in _fetch
    start, length = object_indexes[object_id]
IndexError: list index out of range

**Comment by alice-cool** [comment]
我感觉随机数很重要，我不知道论文里的随机数是多少，默认的代码设置精度达不到



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月25日(星期五) 下午4:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zhiquan-Wen/D-VQA] 代码复现问题 (Issue #4)




 是正常现象，说明模型开始过度估计偏差了应该。。。我这边也是这样
 
 
 | |
 Shandong University
 |
 |
 ***@***.***
 |
 在2022年3月25日 ***@***.***&gt; 写道：
 
 我在up_down+d_vqa 跑，最高时在第20epoch 是59.53，后面几轮就开始降了一直降到34.36，这个是正常现象吗？

**Comment by alice-cool** [comment]
vqa2.0 就参考“https://github.com/hengyuan-hu/bottom-up-attention-vqa/tree/master/tools”应该能实现吧。我看这里分享vqacp数据集的数据预处理
